In [27]:
import pandas as pd

In [28]:
customers = pd.read_csv('olist_customers_dataset.csv')
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_approved
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00,2016-09-15
74217,46046adea0e222a29259bad3d922fee8,e9722ab28655e07763e0ca2751c61c90,delivered,2016-10-04 10:41:17,2016-10-04,2016-10-21 16:29:32,2016-10-24 16:29:32,2016-11-28 00:00:00,2016-10-04
88472,d207cc272675637bfed0062edffd0818,b8cf418e97ae795672d326288dfab7a7,delivered,2016-10-03 22:06:03,2016-10-04,2016-10-21 14:23:37,2016-10-31 11:07:42,2016-11-23 00:00:00,2016-10-04
24769,3f72d2b757e725cd48a4726f831c7789,e0de521fbb397bd7e83d079fe66357b5,delivered,2016-10-04 13:15:46,2016-10-04,2016-10-10 16:45:50,2016-10-17 11:25:59,2016-11-28 00:00:00,2016-10-04
32068,79ffdd52a918bbe867895a4b183d6457,f9808148a262b51d20e2d777eee6676c,delivered,2016-10-04 12:06:11,2016-10-04,2016-10-25 14:16:48,2016-10-26 16:41:21,2016-11-24 00:00:00,2016-10-04

In [29]:
df = pd.read_csv('olist_orders_dataset.csv')
df.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [30]:
df['order_approved_at'] = pd.to_datetime(df['order_approved_at'])
df['order_approved_at'] = df['order_approved_at'].dt.date
df['order_approved'] = pd.to_datetime(df['order_approved_at'])
df = df.sort_values(by=['order_approved'])
df['order_approved'].isnull().sum()
df = df.dropna(subset=['order_approved'])
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_approved
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00,2016-09-15
74217,46046adea0e222a29259bad3d922fee8,e9722ab28655e07763e0ca2751c61c90,delivered,2016-10-04 10:41:17,2016-10-04,2016-10-21 16:29:32,2016-10-24 16:29:32,2016-11-28 00:00:00,2016-10-04
88472,d207cc272675637bfed0062edffd0818,b8cf418e97ae795672d326288dfab7a7,delivered,2016-10-03 22:06:03,2016-10-04,2016-10-21 14:23:37,2016-10-31 11:07:42,2016-11-23 00:00:00,2016-10-04
24769,3f72d2b757e725cd48a4726f831c7789,e0de521fbb397bd7e83d079fe66357b5,delivered,2016-10-04 13:15:46,2016-10-04,2016-10-10 16:45:50,2016-10-17 11:25:59,2016-11-28 00:00:00,2016-10-04
32068,79ffdd52a918bbe867895a4b183d6457,f9808148a262b51d20e2d777eee6676c,delivered,2016-10-04 12:06:11,2016-10-04,2016-10-25 14:16:48,2016-10-26 16:41:21,2016-11-24 00:00:00,2016-10-04
...,...,...,...,...,...,...,...,...,...
88097,35a972d7f8436f405b56e36add1a7140,898b7fee99c4e42170ab69ba59be0a8b,delivered,2018-08-29 15:00:37,2018-08-29,2018-08-29 16:57:00,2018-08-30 16:23:36,2018-09-05 00:00:00,2018-08-29
69678,03ef5dedbe7492bdae72eec50764c43f,496630b6740bcca28fce9ba50d8a26ef,delivered,2018-08-29 14:52:00,2018-08-29,2018-08-29 20:01:00,2018-08-30 16:36:59,2018-09-03 00:00:00,2018-08-29
30077,0b223d92c27432930dfe407c6aea3041,e60df9449653a95af4549bbfcb18a6eb,delivered,2018-08-29 14:18:23,2018-08-29,2018-08-29 15:29:00,2018-08-30 16:24:55,2018-09-04 00:00:00,2018-08-29
5774,d70442bc5e3cb7438da497cc6a210f80,10a79ef2783cae3d8d678e85fde235ac,delivered,2018-08-29 10:22:35,2018-08-29,2018-08-29 19:57:00,2018-08-30 16:03:19,2018-09-04 00:00:00,2018-08-29
62360,54282e97f61c23b78330c15b154c867d,4b7decb9b58e2569548b8b4c8e20e8d7,shipped,2018-09-03 09:06:57,2018-09-03,2018-09-04 15:25:00,NaN,2018-09-06 00:00:00,2018-09-03

In [31]:
df2 = pd.read_csv('olist_order_items_dataset.csv')
df2

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [32]:
orders_total = df.merge(df2,on=['order_id'],how= 'inner' )
orders_total.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_approved,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00,2016-09-15,1,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
1,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00,2016-09-15,2,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
2,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00,2016-09-15,3,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
3,46046adea0e222a29259bad3d922fee8,e9722ab28655e07763e0ca2751c61c90,delivered,2016-10-04 10:41:17,2016-10-04,2016-10-21 16:29:32,2016-10-24 16:29:32,2016-11-28 00:00:00,2016-10-04,1,79bcd1f7f00535c801244eb999d8d290,99eaacc9e6046db1c82b163c5f84869f,2016-10-21 16:29:32,199.00,15.98
4,d207cc272675637bfed0062edffd0818,b8cf418e97ae795672d326288dfab7a7,delivered,2016-10-03 22:06:03,2016-10-04,2016-10-21 14:23:37,2016-10-31 11:07:42,2016-11-23 00:00:00,2016-10-04,1,107177bf61755f05c604fe57e02467d6,cca3071e3e9bb7d12640c9fbe2301306,2016-10-21 16:23:06,119.90,13.56

In [33]:
orders_total=orders_total.drop(columns = ['order_status','order_purchase_timestamp','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date','shipping_limit_date','order_approved_at'])

In [34]:
orders_total['order_approved'] = pd.to_datetime(
    orders_total['order_approved']
)

orders_total['day'] = orders_total['order_approved'].dt.date

orders_total['daily_gmv'] = (
    orders_total.groupby('day')['price'].transform('sum')
)

orders_total['daily_customers'] = (
    orders_total.groupby('day')['customer_id'].transform('nunique')
)

orders_total['daily_avg_spend_per_customer'] = (
    orders_total['daily_gmv']
    / orders_total['daily_customers']
)

orders_total['daily_active_sellers'] = (
    orders_total.groupby('day')['seller_id'].transform('nunique')
)

orders_total['daily_gmv_per_active_seller'] = (
    orders_total['daily_gmv']
    / orders_total['daily_active_sellers']
)

In [35]:
orders_total

,order_id,customer_id,order_approved,order_item_id,product_id,seller_id,price,freight_value,day,daily_gmv,daily_customers,daily_avg_spend_per_customer,daily_active_sellers,daily_gmv_per_active_seller
0,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,2016-09-15,1,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,44.99,2.83,2016-09-15,134.97,1,134.970000,1,134.970000
1,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,2016-09-15,2,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,44.99,2.83,2016-09-15,134.97,1,134.970000,1,134.970000
2,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,2016-09-15,3,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,44.99,2.83,2016-09-15,134.97,1,134.970000,1,134.970000
3,46046adea0e222a29259bad3d922fee8,e9722ab28655e07763e0ca2751c61c90,2016-10-04,1,79bcd1f7f00535c801244eb999d8d290,99eaacc9e6046db1c82b163c5f84869f,199.00,15.98,2016-10-04,2443.57,19,128.608947,16,152.723125
4,d207cc272675637bfed0062edffd0818,b8cf418e97ae795672d326288dfab7a7,2016-10-04,1,107177bf61755f05c604fe57e02467d6,cca3071e3e9bb7d12640c9fbe2301306,119.90,13.56,2016-10-04,2443.57,19,128.608947,16,152.723125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112630,03ef5dedbe7492bdae72eec50764c43f,496630b6740bcca28fce9ba50d8a26ef,2018-08-29,1,c7f27c5bef2338541c772b5776403e6a,7d7866a99a8656a42c7ff6352a433410,24.90,8.33,2018-08-29,1987.63,15,132.508667,17,116.919412
112631,0b223d92c27432930dfe407c6aea3041,e60df9449653a95af4549bbfcb18a6eb,2018-08-29,1,2b4472df15512a2825ae86fd9ae79335,67bf6941ba2f1fa1d02c375766bc3e53,209.00,46.48,2018-08-29,1987.63,15,132.508667,17,116.919412
112632,0b223d92c27432930dfe407c6aea3041,e60df9449653a95af4549bbfcb18a6eb,2018-08-29,2,2b4472df15512a2825ae86fd9ae79335,67bf6941ba2f1fa1d02c375766bc3e53,209.00,46.48,2018-08-29,1987.63,15,132.508667,17,116.919412
112633,d70442bc5e3cb7438da497cc6a210f80,10a79ef2783cae3d8d678e85fde235ac,2018-08-29,1,9a8706b8c060b16e5f0d2925f20bc35b,0be8ff43f22e456b4e0371b2245e4d01,6.90,7.39,2018-08-29,1987.63,15,132.508667,17,116.919412
112634,54282e97f61c23b78330c15b154c867d,4b7decb9b58e2569548b8b4c8e20e8d7,2018-09-03,1,b98992ea80b467987a7fbb88e7f2076a,25be943a321c8938947bdaabca979a90,145.00,21.46,2018-09-03,145.00,1,145.000000,1,145.000000

In [36]:
orders_total.columns

Index(['order_id', 'customer_id', 'order_approved', 'order_item_id',
       'product_id', 'seller_id', 'price', 'freight_value', 'day', 'daily_gmv',
       'daily_customers', 'daily_avg_spend_per_customer',
       'daily_active_sellers', 'daily_gmv_per_active_seller'],
      dtype='str')

In [37]:
orders_total.to_csv('sales_data.csv', index=False)

In [38]:
# 1. Convert timestamp into datetime
orders_total['order_approved'] = pd.to_datetime(
    orders_total['order_approved']
)

# 2. Create only the DATE part
orders_total['date'] = orders_total['order_approved'].dt.date


# 3. Create day-wise base KPIs
daily_kpi = (
    orders_total
    .groupby('date')
    .agg(
        revenue=('price', 'sum'),
        customer_count=('customer_id', 'nunique'),
        active_sellers=('seller_id', 'nunique')
    )
    .reset_index()
)


# 4. Derived KPIs
daily_kpi['avg_spend_per_customer'] = (
    daily_kpi['revenue'] /
    daily_kpi['customer_count']
)

daily_kpi['gmv_per_active_seller'] = (
    daily_kpi['revenue'] /
    daily_kpi['active_sellers']
)


# 5. Make date the primary-key-like index
daily_kpi = daily_kpi.set_index('date')


daily_kpi.head()
daily_kpi.shape

(610, 5)

In [39]:
daily_kpi.to_csv('sales_kpi_df.csv', index=False)

In [40]:
sales_data = pd.read_csv("sales_data.csv")
sales_data.head()
sales_data.shape

(112635, 14)

In [41]:
sales_data.isnull().sum()

order_id                        0
customer_id                     0
order_approved                  0
order_item_id                   0
product_id                      0
seller_id                       0
price                           0
freight_value                   0
day                             0
daily_gmv                       0
daily_customers                 0
daily_avg_spend_per_customer    0
daily_active_sellers            0
daily_gmv_per_active_seller     0
dtype: int64

In [42]:
sales_data.dtypes

order_id                            str
customer_id                         str
order_approved                      str
order_item_id                     int64
product_id                          str
seller_id                           str
price                           float64
freight_value                   float64
day                                 str
daily_gmv                       float64
daily_customers                   int64
daily_avg_spend_per_customer    float64
daily_active_sellers              int64
daily_gmv_per_active_seller     float64
dtype: object

In [45]:
sales_data['order_approved'] = pd.to_datetime(sales_data['order_approved'])

df =sales_data.sort_values(by='order_approved')
sales_data.head()

,order_id,customer_id,order_approved,order_item_id,product_id,seller_id,price,freight_value,day,daily_gmv,daily_customers,daily_avg_spend_per_customer,daily_active_sellers,daily_gmv_per_active_seller
0,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,2016-09-15,1,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,44.99,2.83,2016-09-15,134.97,1,134.970000,1,134.970000
1,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,2016-09-15,2,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,44.99,2.83,2016-09-15,134.97,1,134.970000,1,134.970000
2,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,2016-09-15,3,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,44.99,2.83,2016-09-15,134.97,1,134.970000,1,134.970000
22,711b9be9c346d9ecdb9d38a5e1e7e39b,81e4aed5ab4253757305267b80712689,2016-10-04,1,d6f3bd7b1fc04fb1a2effb51ae44ab17,4b1eaadf791bdbbad8c4a35b65236d52,189.90,12.87,2016-10-04,2443.57,19,128.608947,16,152.723125
21,cd3b8574c82b42fc8129f6d502690c3e,7812fcebfc5e8065d31e1bb5f0017dae,2016-10-04,1,e2a1d45a73dc7f5a7f9236b043431b89,b499c00f28f4b7069ff6550af8c1348a,29.99,10.96,2016-10-04,2443.57,19,128.608947,16,152.723125

In [46]:



# ============================================================
# 1. ADD customer_unique_id TO MAIN DATAFRAME
# ============================================================

# Only run this merge if customer_unique_id is not already present
if "customer_unique_id" not in df.columns:

    df = df.merge(
        customers[
            ["customer_id", "customer_unique_id"]
        ],
        on="customer_id",
        how="left"
    )


# ============================================================
# 2. PREPARE DATE
# ============================================================

df["day"] = pd.to_datetime(df["order_approved"]).dt.normalize()


# ============================================================
# 3. FIND FIRST PURCHASE DAY OF EVERY CUSTOMER
# ============================================================

first_customer_day = (
    df.groupby("customer_unique_id")["day"]
      .min()
)

df["customer_first_day"] = (
    df["customer_unique_id"]
    .map(first_customer_day)
)


# ============================================================
# 4. FIND FIRST ACTIVE DAY OF EVERY SELLER
# ============================================================

first_seller_day = (
    df.groupby("seller_id")["day"]
      .min()
)

df["seller_first_day"] = (
    df["seller_id"]
    .map(first_seller_day)
)


# ============================================================
# 5. BASIC DAILY KPIs
# ============================================================

daily_df = (
    df.groupby("day")
      .agg(

          # Revenue / GMV
          daily_gmv=("price", "sum"),

          # Total unique orders
          daily_orders=("order_id", "nunique"),

          # Actual unique customers
          daily_customers=("customer_unique_id", "nunique"),

          # Number of items sold
          units_sold=("order_item_id", "count"),

          # Sellers who actually sold something that day
          active_sellers=("seller_id", "nunique"),

          # Average price of an individual item
          average_item_price=("price", "mean")
      )
      .reset_index()
)


# ============================================================
# 6. CUSTOMER / ORDER DRIVER METRICS
# ============================================================

# Orders per customer
daily_df["orders_per_customer"] = (
    daily_df["daily_orders"]
    / daily_df["daily_customers"]
)


# Average Order Value
daily_df["average_order_value"] = (
    daily_df["daily_gmv"]
    / daily_df["daily_orders"]
)


# Items per order
daily_df["items_per_order"] = (
    daily_df["units_sold"]
    / daily_df["daily_orders"]
)


# Average customer spending
daily_df["avg_spend_per_customer"] = (
    daily_df["daily_gmv"]
    / daily_df["daily_customers"]
)


# ============================================================
# 7. NEW CUSTOMERS
# ============================================================

new_customers = (
    df[
        df["day"] == df["customer_first_day"]
    ]
    .groupby("day")["customer_unique_id"]
    .nunique()
    .rename("new_customers")
)


daily_df = daily_df.merge(
    new_customers,
    on="day",
    how="left"
)


# ============================================================
# 8. RETURNING CUSTOMERS
# ============================================================

returning_customers = (
    df[
        df["day"] > df["customer_first_day"]
    ]
    .groupby("day")["customer_unique_id"]
    .nunique()
    .rename("returning_customers")
)


daily_df = daily_df.merge(
    returning_customers,
    on="day",
    how="left"
)


# Replace missing values with 0
daily_df["new_customers"] = (
    daily_df["new_customers"]
    .fillna(0)
    .astype(int)
)

daily_df["returning_customers"] = (
    daily_df["returning_customers"]
    .fillna(0)
    .astype(int)
)


# ============================================================
# 9. NEW SELLERS
# ============================================================

new_sellers = (
    df[
        df["day"] == df["seller_first_day"]
    ]
    .groupby("day")["seller_id"]
    .nunique()
    .rename("new_sellers")
)


daily_df = daily_df.merge(
    new_sellers,
    on="day",
    how="left"
)


daily_df["new_sellers"] = (
    daily_df["new_sellers"]
    .fillna(0)
    .astype(int)
)


# ============================================================
# 10. TOTAL SELLER COUNT
# ============================================================

# seller_count = total seller base accumulated up to that day

daily_df = daily_df.sort_values("day")

daily_df["seller_count"] = (
    daily_df["new_sellers"]
    .cumsum()
)


# ============================================================
# 11. SELLER ORDERS
# ============================================================

# Important:
# One order can contain products from multiple sellers.
# Therefore count unique order-seller combinations.

seller_orders = (
    df[
        ["day", "seller_id", "order_id"]
    ]
    .drop_duplicates()
    .groupby("day")
    .size()
    .rename("seller_orders")
)


daily_df = daily_df.merge(
    seller_orders,
    on="day",
    how="left"
)


# ============================================================
# 12. ORDERS PER ACTIVE SELLER
# ============================================================

daily_df["orders_per_seller"] = (
    daily_df["seller_orders"]
    / daily_df["active_sellers"]
)


# ============================================================
# 13. UNITS SOLD PER ACTIVE SELLER
# ============================================================

daily_df["units_sold_per_seller"] = (
    daily_df["units_sold"]
    / daily_df["active_sellers"]
)


# ============================================================
# 14. GMV / REVENUE PER ACTIVE SELLER
# ============================================================

daily_df["gmv_per_active_seller"] = (
    daily_df["daily_gmv"]
    / daily_df["active_sellers"]
)


# ============================================================
# 15. SORT DATA BY DAY
# ============================================================

daily_df = (
    daily_df
    .sort_values("day")
    .reset_index(drop=True)
)


# ============================================================
# 16. CREATE DAY INDEX: 1, 2, 3, 4 ...
# ============================================================

daily_df["day_index"] = range(
    1,
    len(daily_df) + 1
)


# Make day_index actual dataframe index
daily_df = daily_df.set_index("day_index")


# ============================================================
# 17. FINAL COLUMN ORDER
# ============================================================

daily_df = daily_df[[
    
    "day",

    # Main KPI
    "daily_gmv",

    # Customer metrics
    "daily_customers",
    "new_customers",
    "returning_customers",
    "orders_per_customer",
    "avg_spend_per_customer",

    # Order metrics
    "daily_orders",
    "average_order_value",
    "items_per_order",

    # Product metrics
    "units_sold",
    "average_item_price",

    # Seller metrics
    "seller_count",
    "new_sellers",
    "active_sellers",
    "seller_orders",
    "orders_per_seller",
    "units_sold_per_seller",
    "gmv_per_active_seller"
]]


# ============================================================
# 18. DISPLAY
# ============================================================

daily_df.head()

,day,daily_gmv,daily_customers,new_customers,returning_customers,orders_per_customer,avg_spend_per_customer,daily_orders,average_order_value,items_per_order,units_sold,average_item_price,seller_count,new_sellers,active_sellers,seller_orders,orders_per_seller,units_sold_per_seller,gmv_per_active_seller
day_index,,,,,,,,,,,,,,,,,,,
1,2016-09-15,134.97,1,1,0,1.000000,134.970000,1,134.970000,3.000000,3,44.990000,1,1,1,1,1.000000,3.000000,134.970000
2,2016-10-04,2443.57,19,19,0,1.000000,128.608947,19,128.608947,1.052632,20,122.178500,17,16,16,19,1.187500,1.250000,152.723125
3,2016-10-05,1622.05,10,10,0,1.000000,162.205000,10,162.205000,1.400000,14,115.860714,23,6,8,10,1.250000,1.750000,202.756250
4,2016-10-06,17515.56,108,108,0,1.000000,162.181111,108,162.181111,1.148148,124,141.254516,81,58,69,110,1.594203,1.797101,253.848696
5,2016-10-07,10559.80,56,56,0,1.017857,188.567857,57,185.259649,1.280702,73,144.654795,104,23,47,57,1.212766,1.553191,224.676596

In [47]:
daily_df.to_csv('daily_df.csv', index=False)